In [1]:
import torch
print(torch.__version__)
print(torch.cuda.is_available())

2.6.0
False


In [4]:
tensor2d = torch.tensor([[1, 2, 3], [4, 5, 6]])
print(tensor2d)
print(tensor2d.dtype)
print(tensor2d.shape)
print(tensor2d.device)
print(tensor2d.requires_grad)
print(tensor2d.grad)

tensor([[1, 2, 3],
        [4, 5, 6]])
torch.int64
torch.Size([2, 3])
cpu
False
None


In [19]:
tensor2d.T
tensor2d.numel()

6

In [12]:
tensor2d @ tensor2d.T
print(tensor2d.sum())

tensor2d.min()

tensor(21)


tensor(1)

In [14]:
import torch.nn.functional as F
y = torch.tensor([1.0])
x1 = torch.tensor([1.1])
w1 = torch.tensor([2.2])
b = torch.tensor([0.0])
z = x1 * w1 + b
a = torch.sigmoid(z)
print(a)
loss = F.binary_cross_entropy(a, y)
print(loss)

tensor([0.9183])
tensor(0.0852)


In [15]:
from torch.autograd import grad
w1 = torch.tensor([2.2], requires_grad=True)
b = torch.tensor([0.0], requires_grad=True)
z = x1 * w1 + b
a = torch.sigmoid(z)
loss = F.binary_cross_entropy(a, y)
print(loss)
w1_grad = grad(loss, w1, create_graph=True)
b1_grad = grad(loss, b, create_graph=True)
print(w1_grad)
print(b1_grad)


tensor(0.0852, grad_fn=<BinaryCrossEntropyBackward0>)
(tensor([-0.0898], grad_fn=<MulBackward0>),)
(tensor([-0.0817], grad_fn=<SigmoidBackwardBackward0>),)


In [16]:
print(w1.grad)
print(b.grad)
loss.backward()
print(w1.grad)
print(b.grad)

None
None
tensor([-0.0898])
tensor([-0.0817])


In [30]:
class NeuralNetwork(torch.nn.Module):
    def __init__(self, num_input, output_num):
        super().__init__()
        self.layers = torch.nn.Sequential(
            torch.nn.Linear(num_input, 30),
            torch.nn.ReLU(),
            torch.nn.Linear(30, 20),
            torch.nn.ReLU(),
            torch.nn.Linear(20, output_num)
        )


    def forward(self, x):
        logits = self.layers(x)
        return logits

model = NeuralNetwork(50,3)
print(model)

NeuralNetwork(
  (layers): Sequential(
    (0): Linear(in_features=50, out_features=30, bias=True)
    (1): ReLU()
    (2): Linear(in_features=30, out_features=20, bias=True)
    (3): ReLU()
    (4): Linear(in_features=20, out_features=3, bias=True)
  )
)


In [28]:
total_params = sum([p.numel() for p in model.parameters()])
print(total_params)
total_params_grad = sum([p.numel() for p in model.parameters() if p.requires_grad])
print(total_params_grad)

2213
2213


In [31]:
print(model.layers[0].weight)
print(model.layers[0].weight.numel())
print(model.layers[0].weight.shape)


Parameter containing:
tensor([[ 0.0279,  0.1232, -0.0186,  ...,  0.0643, -0.0302,  0.0879],
        [-0.1123,  0.0179,  0.0385,  ..., -0.0914, -0.0333,  0.0037],
        [ 0.0834, -0.0733,  0.1082,  ...,  0.0274,  0.0327, -0.1286],
        ...,
        [-0.0069, -0.1127,  0.0692,  ...,  0.0052, -0.0443, -0.0623],
        [-0.0048, -0.0890, -0.0262,  ...,  0.0290,  0.1033, -0.0010],
        [-0.1341, -0.0785,  0.0214,  ...,  0.0545, -0.0357,  0.1413]],
       requires_grad=True)
1500
torch.Size([30, 50])


In [33]:
torch.manual_seed(123)
model = NeuralNetwork(50, 3)
print(model.layers[0].weight)

Parameter containing:
tensor([[-0.0577,  0.0047, -0.0702,  ...,  0.0222,  0.1260,  0.0865],
        [ 0.0502,  0.0307,  0.0333,  ...,  0.0951,  0.1134, -0.0297],
        [ 0.1077, -0.1108,  0.0122,  ...,  0.0108, -0.1049, -0.1063],
        ...,
        [-0.0787,  0.1259,  0.0803,  ...,  0.1218,  0.1303, -0.1351],
        [ 0.1359,  0.0175, -0.0673,  ...,  0.0674,  0.0676,  0.1058],
        [ 0.0790,  0.1343, -0.0293,  ...,  0.0344, -0.0971, -0.0509]],
       requires_grad=True)


In [34]:
print(model.layers[0].weight.shape) # 这里x与weight的转置相乘，所以weight是[30,50],运算时转置成【50，30】

torch.Size([30, 50])


In [44]:
torch.manual_seed(123)
x = torch.rand((1,50))
print(x)
out = model(x)
print(out)


tensor([[0.2961, 0.5166, 0.2517, 0.6886, 0.0740, 0.8665, 0.1366, 0.1025, 0.1841,
         0.7264, 0.3153, 0.6871, 0.0756, 0.1966, 0.3164, 0.4017, 0.1186, 0.8274,
         0.3821, 0.6605, 0.8536, 0.5932, 0.6367, 0.9826, 0.2745, 0.6584, 0.2775,
         0.8573, 0.8993, 0.0390, 0.9268, 0.7388, 0.7179, 0.7058, 0.9156, 0.4340,
         0.0772, 0.3565, 0.1479, 0.5331, 0.4066, 0.2318, 0.4545, 0.9737, 0.4606,
         0.5159, 0.4220, 0.5786, 0.9455, 0.8057]])
tensor([[-0.1262,  0.1080, -0.1792]], grad_fn=<AddmmBackward0>)


In [46]:
with torch.no_grad():
    print(model(x))

tensor([[-0.1262,  0.1080, -0.1792]])


In [49]:
with torch.no_grad():
    out = torch.softmax(model(x), dim=-1)
print(out)

tensor([[0.3113, 0.3934, 0.2952]])


In [50]:
X_train = torch.tensor([
    [-1.2, 3.1],
    [-0.9, 2.9],
    [-0.5, 2.6],
    [2.3, -1.1],
    [2.7, -1.5]
])

y_train = torch.tensor([0, 0, 0, 1, 1])
X_test = torch.tensor([
    [-0.8, 2.8],
    [2.6, -1.6],
])

y_test = torch.tensor([0, 1])

In [67]:
from torch.utils.data import Dataset
class ToyDataLoader(Dataset):
    def __init__(self, x, y):
        self.features = x
        self.labels = y
    def __getitem__(self, idx):
        return self.features[idx], self.labels[idx]
    def __len__(self):
        return self.labels.size()[0]

In [68]:
train_ds = ToyDataLoader(X_train, y_train)
test_ds = ToyDataLoader(X_test, y_test)
len(train_ds)

5

In [73]:
from torch.utils.data import DataLoader
torch.manual_seed(123)
train_loader = DataLoader(
    dataset=train_ds,
    batch_size=2,
    shuffle=True,
    num_workers=0
)
test_loader = DataLoader(
    dataset=test_ds,
    batch_size=2,
    shuffle=True,
    num_workers=0
)
for idx, (x, y) in enumerate(train_loader):
    print(f"Batch {idx}: ",x ,y)

Batch 0:  tensor([[ 2.3000, -1.1000],
        [-0.9000,  2.9000]]) tensor([1, 0])
Batch 1:  tensor([[-1.2000,  3.1000],
        [-0.5000,  2.6000]]) tensor([0, 0])
Batch 2:  tensor([[ 2.7000, -1.5000]]) tensor([1])


In [78]:
torch.manual_seed(123)

train_loader = DataLoader(
    dataset=train_ds,
    batch_size=2,
    shuffle=True,
    num_workers=0,
    drop_last=True
)
for idx, (x, y) in enumerate(train_loader):
    print(f"Batch {idx}: ",x ,y)


Batch 0:  tensor([[ 2.3000, -1.1000],
        [-0.9000,  2.9000]]) tensor([1, 0])
Batch 1:  tensor([[-1.2000,  3.1000],
        [-0.5000,  2.6000]]) tensor([0, 0])


In [80]:
torch.manual_seed(123)
model = NeuralNetwork(2,2)
optimizer = torch.optim.SGD(model.parameters(), lr=0.5)

epoch_nums = 3

for epoch in range(epoch_nums):
    model.train()
    for batch_id, (features, labels) in enumerate(train_loader):
        logits = model(features)
        loss = F.cross_entropy(logits, labels)

        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
        
        print(f"Epochs {epoch + 1:02d}/{epoch_nums:02d}, "
              f" | Batch {batch_id + 1:02d}/{len(train_loader):02d}"
              f" | Train Loss {loss:.3f}")

            

Epochs 01/03,  | Batch 01/02 | Train Loss 0.749
Epochs 01/03,  | Batch 02/02 | Train Loss 0.645
Epochs 02/03,  | Batch 01/02 | Train Loss 0.442
Epochs 02/03,  | Batch 02/02 | Train Loss 0.126
Epochs 03/03,  | Batch 01/02 | Train Loss 0.027
Epochs 03/03,  | Batch 02/02 | Train Loss 0.004


In [81]:
model.eval()
with torch.no_grad():
    output = model(X_train)
print(output)

tensor([[ 2.8569, -4.1618],
        [ 2.5382, -3.7548],
        [ 2.0944, -3.1820],
        [-1.4814,  1.4816],
        [-1.7176,  1.7342]])


In [83]:
torch.set_printoptions(sci_mode=False)
probas = torch.softmax(output, dim=1)
print(probas)
predictions = torch.argmax(probas, dim=1)
print(predictions)

tensor([[    0.9991,     0.0009],
        [    0.9982,     0.0018],
        [    0.9949,     0.0051],
        [    0.0491,     0.9509],
        [    0.0307,     0.9693]])
tensor([0, 0, 0, 1, 1])


In [85]:
predictions = torch.argmax(output, dim=1)
print(predictions)

tensor([0, 0, 0, 1, 1])


In [86]:
predictions == y_train

tensor([True, True, True, True, True])

In [87]:
torch.sum(predictions==y_train)

tensor(5)

In [94]:
def compute_accuracy(model, dataloader):
    model.eval()
    correct = 0
    total_samples = 0
    with torch.no_grad():
        for idx, (features, labels) in enumerate(dataloader):
            logits = model(features)
            probas = torch.softmax(logits, dim=1)
            predictions = torch.argmax(probas, dim=1)
            print(predictions)
            compare = labels == predictions
            print("compare: ", compare)
            correct += torch.sum(compare)
            print("correct: ", correct)
            total_samples += len(features)
            print("total samples: ", total_samples)
    return (correct / total_samples).item()

compute_accuracy(model, train_loader)

tensor([1, 0])
compare:  tensor([True, True])
correct:  tensor(2)
total samples:  2
tensor([0, 0])
compare:  tensor([True, True])
correct:  tensor(4)
total samples:  4


1.0

In [95]:
compute_accuracy(model, test_loader)

tensor([0, 1])
compare:  tensor([True, True])
correct:  tensor(2)
total samples:  2


1.0